version: "3.7"


services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    expose:
      - 5000
    networks:
      - my-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask

  mysql:
    build: ./mysql
    container_name: mysql
    restart: always
    expose:
      - 3306
    # ports:
    #   - 3306:3306
    networks:
      - my-network
    depends_on:
      - flask

networks:
  my-network:
